// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuGE1r5OpFgYlLhfPHgdKbxDoy6A9X4b0',
    appId: '1:687907492866:web:6915cbe5a7d73cae2a831b',
    messagingSenderId: '687907492866',
    projectId: 'kaki-f9832',
    authDomain: 'kaki-f9832.firebaseapp.com',
    storageBucket: 'kaki-f9832.firebasestorage.app',
    measurementId: 'G-G8YLBS0ERM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeQl4oLMUu807w0ylWTsBmQAoLw6e3ZoE',
    appId: '1:687907492866:android:7d4f0e5c30f7a92d2a831b',
    messagingSenderId: '687907492866',
    projectId: 'kaki-f9832',
    storageBucket: 'kaki-f9832.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADsTVEqDs6SEwLADIsV_6vRVrcfsgzD6Y',
    appId: '1:687907492866:ios:5bc0999e199cd0222a831b',
    messagingSenderId: '687907492866',
    projectId: 'kaki-f9832',
    storageBucket: 'kaki-f9832.firebasestorage.app',
    androidClientId: '687907492866-19luigevj4hkhgffsefp8vhgqfjk302a.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarm',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADsTVEqDs6SEwLADIsV_6vRVrcfsgzD6Y',
    appId: '1:687907492866:ios:5bc0999e199cd0222a831b',
    messagingSenderId: '687907492866',
    projectId: 'kaki-f9832',
    storageBucket: 'kaki-f9832.firebasestorage.app',
    androidClientId: '687907492866-19luigevj4hkhgffsefp8vhgqfjk302a.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuGE1r5OpFgYlLhfPHgdKbxDoy6A9X4b0',
    appId: '1:687907492866:web:6915cbe5a7d73cae2a831b',
    messagingSenderId: '687907492866',
    projectId: 'kaki-f9832',
    authDomain: 'kaki-f9832.firebaseapp.com',
    storageBucket: 'kaki-f9832.firebasestorage.app',
    measurementId: 'G-G8YLBS0ERM',
  );
}
